DZ04/SeizmoloskiZavod/SeizmoloskiZavod.Web/Controllers/SeizmografiController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SeizmoloskiZavod.Bll;

namespace SeizmoloskiZavod.Web.Controllers
{
    public class SeizmografiController : Controller
    {
        // GET: Seizmografi
        public ActionResult Index()
        {
            var postaje = Postaja.Get().ToList();
            ViewData["postaje"] = postaje;
            return View(Seizmograf.Get());
        }

        // GET: Seizmografi/Details/5
        public ActionResult Details(int id)
        {
            var seizmogrami = Seizmogram.Get().ToList();
            ViewData["seizmogrami"] = seizmogrami;
            return View(Seizmograf.Get(id));
        }

        // GET: Seizmografi/Create
        public ActionResult Create()
        {
            ViewBag.IdPostajeList = new SelectList(Postaja.Get(), "IdPostaje", "NazPostaje");
            return View(Seizmograf.New());
        }

        // POST: Seizmografi/Create
        [HttpPost]
        public ActionResult Create(string NazSeizmografa, int IdPostajeSeizmografa, double VisinaSeizmografa, double LatitudaSeizmografa, double LongitudaSeizmografa)
        {

            Seizmograf seizmograf = Seizmograf.New();
            try
            {
                //ViewBag.IdPostajeSeizmografa = (new SelectList(Postaja.Get(), "IdPostaje", "NazPostaje"));

                seizmograf.IdPostajeSeizmografa = IdPostajeSeizmografa;
                seizmograf.VisinaSeizmografa = VisinaSeizmografa;
                seizmograf.LatitudaSeizmografa = LatitudaSeizmografa;
                seizmograf.LongitudaSeizmografa = LongitudaSeizmografa;
                seizmograf.NazSeizmografa = NazSeizmografa;

                seizmograf = seizmograf.Save();
                return RedirectToAction("Details", new { id = seizmograf.IdSeizmografa });
            }
            catch (Csla.Validation.ValidationException ex)
            {
                ViewBag.Pogreska = ex.Message;
                if (seizmograf.BrokenRulesCollection.Count > 0)
                {
                    List<string> errors = new List<string>();
                    foreach (Csla.Validation.BrokenRule rule in seizmograf.BrokenRulesCollection)
                    {
                        errors.Add(string.Format("{0}: {1}", rule.Property, rule.Description));
                        ModelState.AddModelError(rule.Property, rule.Description);
                    }
                    ViewBag.ErrorsList = errors;
                }
                return View(seizmograf);
            }
            catch (Csla.DataPortalException ex)
            {
                ViewBag.Pogreska = ex.BusinessException.Message;
                return View(seizmograf);
            }
            catch (Exception ex)
            {
                ViewBag.Pogreska = ex.Message;
                return View(seizmograf);
            }
        }

        public ActionResult Mjerenje()
        {
            return View(SeizmografInfoList.Get());
        }

        [HttpPost]
        public ActionResult Mjerenje(FormCollection formCollection)
        {
            if (ModelState.IsValid)
            {
                foreach (Seizmograf s in Seizmograf.Get())
                {
                    if (formCollection[s.IdSeizmografa.ToString()] != null)
                    {
                        Seizmogram seizmogram = Seizmogram.New();
                        seizmogram.IdSeizmografa = s.IdSeizmografa;
                        seizmogram.PomakIZSeizmograma = Math.Round(VrijednostiMjerenja.GetRandomNumber(0.00001, 0.50000), 5, MidpointRounding.AwayFromZero);
                        seizmogram.PomakSJSeizmograma = Math.Round(VrijednostiMjerenja.GetRandomNumber(0.00001, 0.50000), 5, MidpointRounding.AwayFromZero);
                        seizmogram.PomakVertSeizmograma = Math.Round(VrijednostiMjerenja.GetRandomNumber(0.00001, 0.50000), 5, MidpointRounding.AwayFromZero);
                        seizmogram.DatumVrijemeSeizmograma = DateTime.Now;

                        seizmogram = seizmogram.Save();
                    }
                }
            }
            return RedirectToAction("Index");
        }

        // GET: Seizmografi/Edit/5
        public ActionResult Edit(int id)
        {

            Seizmograf seizmograf = Seizmograf.Get(id);
            ViewBag.IdPostajeList = new SelectList(Postaja.Get(), "IdPostaje", "NazPostaje");

            return View(seizmograf);
        }

        // POST: Seizmografi/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, int IdPostajeSeizmografa, double VisinaSeizmografa, double LatitudaSeizmografa, double LongitudaSeizmografa, string NazSeizmografa)
        {
            Seizmograf seizmograf = null;
            try
            {
                seizmograf = Seizmograf.Get(id);
                seizmograf.IdPostajeSeizmografa = IdPostajeSeizmografa;
                seizmograf.VisinaSeizmografa = VisinaSeizmografa;
                seizmograf.LatitudaSeizmografa = LatitudaSeizmografa;
                seizmograf.LongitudaSeizmografa = LongitudaSeizmografa;
                seizmograf.NazSeizmografa = NazSeizmografa;
                seizmograf.Save();
                return RedirectToAction("Details", new { id = seizmograf.IdSeizmografa });
            }
            catch (Csla.Validation.ValidationException ex)
            {
                ViewBag.Pogreska = ex.Message;
                if (seizmograf.BrokenRulesCollection.Count > 0)
                {
                    List<string> errors = new List<string>();
                    foreach (Csla.Validation.BrokenRule rule in seizmograf.BrokenRulesCollection)
                    {
                        errors.Add(string.Format("{0}: {1}", rule.Property, rule.Description));
                        ModelState.AddModelError(rule.Property, rule.Description);
                    }
                    ViewBag.ErrorsList = errors;
                }
                return View(seizmograf);
            }
            catch (Csla.DataPortalException ex)
            {
                ViewBag.Pogreska = ex.BusinessException.Message;
                return View(seizmograf);
            }
            catch (Exception ex)
            {
                ViewBag.Pogreska = ex.Message;
                return View(seizmograf);
            }
        }

        /*[HttpGet]
        public ActionResult EditPartial(int id)
        {
            Seizmograf seizmograf = null;

            ViewBag.IdPostajeList = new SelectList(Postaja.Get(), "IdPostaje", "NazPostaje");
            try
            {
                seizmograf = Seizmograf.Get(id);
            }
            catch (Exception ex)
            {
                ViewBag.Pogreska = ex.Message;
                return View(seizmograf);
            }
            if (seizmograf != null)
            {

                return PartialView(seizmograf);
            }
            else
            {
                return null;
            }
        }

        [HttpPost]
        public ActionResult EditPartial(Seizmograf seizmograf)
        {
            if (seizmograf == null)
            {
                return null;
            }
            ViewBag.IdPostajeList = new SelectList(Postaja.Get(), "IdPostaje", "NazPostaje");
            if (ModelState.IsValid)
            {
                try
                {
                    seizmograf.Save();
                    return StatusCode(302, Url.Action(nameof(Row), new { id = seizmograf.IdSeizmografa }));

                }
                catch (Exception exc)
                {
                    ModelState.AddModelError(string.Empty, exc.CompleteExceptionMessage());
                    return PartialView(seizmograf);
                }
            }
            else
            {
                return PartialView(seizmograf);
            }
        }*/

        // POST: Seizmografi/Delete/5
        [HttpPost]
        public ActionResult Delete(int id)
        {
            int idPostaje = Seizmograf.Get(id).IdPostajeSeizmografa;

            try
            {
                Seizmograf.Delete(id);
            }
            catch (Exception ex)
            {
                TempData["Pogreska"] = ex.Message;
                return RedirectToAction("/Details", new { id = id });
            }
            return RedirectToAction("../Postaje/Details", new { id = idPostaje });
        }
    }
}

DZ04/SeizmoloskiZavod/SeizmoloskiZavod.Web/Controllers/SeizmogramiController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SeizmoloskiZavod.Bll;

namespace SeizmoloskiZavod.Web.Controllers
{
    public class SeizmogramiController : Controller
    {
        // POST: Seizmogrami/Delete/5
        [HttpPost]
        public ActionResult Delete(int id)
        {
            int idSeizmografa = Seizmogram.Get(id).IdSeizmografa;

            try
            {
                Seizmogram.Delete(id);
            }
            catch (Exception ex)
            {
                TempData["Pogreska"] = ex.Message;
            }
            return RedirectToAction("../Seizmografi/Details", new { id = idSeizmografa });
        }
    }
}

DZ04/SeizmoloskiZavod/SeizmoloskiZavod.Web/Views/Seizmografi/Create.cshtml
@model SeizmoloskiZavod.Bll.Seizmograf

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Stvaranje novog seizmografa</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Seizmograf</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        <b class="control-label col-md-2">Naziv</b>
        <div class="col-md-10">
            @Html.EditorFor(model => model.NazSeizmografa, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NazSeizmografa, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <b class="control-label col-md-2">Naziv postaje</b>
        <div class="col-md-10">
            @Html.DropDownListFor(m => m.IdPostajeSeizmografa, (SelectList)ViewBag.IdPostajeList,
            null, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.IdPostajeSeizmografa, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <b class="control-label col-md-2">Visina</b>
        <div class="col-md-10">
            @Html.EditorFor(model => model.VisinaSeizmografa, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.VisinaSeizmografa, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <b class="control-label col-md-2">Latituda</b>
        <div class="col-md-10">
            @Html.EditorFor(model => model.LatitudaSeizmografa, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LatitudaSeizmografa, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <b class="control-label col-md-2">Longituda</b>
        <div class="col-md-10">
            @Html.EditorFor(model => model.LongitudaSeizmografa, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LongitudaSeizmografa, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

@{Html.RenderPartial("ValidationError");}


<div>
    @Html.ActionLink("Natrag na popis", "Index")
</div>

DZ04/SeizmoloskiZavod/SeizmoloskiZavod.Web/Views/Seizmografi/Delete.cshtml
@model SeizmoloskiZavod.Bll.Seizmograf

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Obriši</h2>

<h3>Jeste li sigurni da želite obrisati?</h3>
<div>
    <h4>Seizmograf</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            <b>Naziv</b>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NazSeizmografa)
        </dd>
        <dt>
            <b>Visina</b>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VisinaSeizmografa)
        </dd>

        <dt>
            <b>Latituda</b>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LatitudaSeizmografa)
        </dd>

        <dt>
            <b>Longituda</b>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LongitudaSeizmografa)
        </dd>

        <dt>
            <b>Naziv postaje</b>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PostajaSeizmografa)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {

        <div class="form-actions no-color">
            <input type="submit" value="Obriši" class="btn btn-default" /> |
            @Html.ActionLink("Natrag na popis", "Index")
        </div>
    }
</div>

DZ04/SeizmoloskiZavod/SeizmoloskiZavod.Web/Views/Seizmografi/Details.cshtml
@using SeizmoloskiZavod.Bll
@model SeizmoloskiZavod.Bll.Seizmograf

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
    IEnumerable<Seizmogram> seizmogrami = ViewData["seizmogrami"] as IEnumerable<Seizmogram>;
}

<h2>Detalji</h2>

<div>
    <h4>Seizmograf</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            <b>Naziv</b>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NazSeizmografa)
        </dd>
        <dt>
            <b>Visina</b>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VisinaSeizmografa)
        </dd>

        <dt>
            <b>Latituda</b>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LatitudaSeizmografa)
        </dd>

        <dt>
            <b>Longituda</b>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LongitudaSeizmografa)
        </dd>

        <dt>
            <b>Naziv postaje</b>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PostajaSeizmografa)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Ažuriraj", "Edit", new { id = Model.IdSeizmografa }) |
    @Html.ActionLink("Natrag na popis", "Index")
</p>

<h2>Zabilježeni seizmogrami</h2>

<table class="table">
    <tr>
        <th>
            <b>Datum i vrijeme</b>
        </th>
        <th>
            <b>Pomak Istok-Zapad</b>
        </th>
        <th>
            <b>Pomak Sjever-Jug</b>
        </th>
        <th>
            <b>Vertikalni Pomak</b>
        </th>
        <th></th>
    </tr>

    @{
        foreach (Seizmogram seizmogram in seizmogrami)
        {
            if (seizmogram != null && seizmogram.IdSeizmografa == Model.IdSeizmografa)
            {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => seizmogram.DatumVrijemeSeizmograma)
        </td>
        <td>
            @Html.DisplayFor(modelItem => seizmogram.PomakIZSeizmograma)
        </td>
        <td>
            @Html.DisplayFor(modelItem => seizmogram.PomakSJSeizmograma)
        </td>
        <td>
            @Html.DisplayFor(modelItem => seizmogram.PomakVertSeizmograma)
        </td>

        <td>
            @using (Html.BeginForm("Delete", "Seizmogrami", new { id = seizmogram.IdSeizmograma }))
            {
                <button class="btn btn-danger">Obriši</button>
            }
        </td>
    </tr>

            }
        }
    }

</table>

DZ04/SeizmoloskiZavod/SeizmoloskiZavod.Web/Views/Seizmografi/Edit.cshtml
@model SeizmoloskiZavod.Bll.Seizmograf

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Ažuriranje</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Seizmograf</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.IdSeizmografa)

    <div class="form-group">
        <b class="control-label col-md-2">Naziv</b>
        <div class="col-md-10">
            @Html.EditorFor(model => model.NazSeizmografa, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NazSeizmografa, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <b class="control-label col-md-2">Naziv postaje</b>
        <div class="col-md-10">
            @Html.DropDownListFor(m => m.IdPostajeSeizmografa, (SelectList)ViewBag.IdPostajeList,
            null, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.IdPostajeSeizmografa, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <b class="control-label col-md-2">Visina</b>
        <div class="col-md-10">
            @Html.EditorFor(model => model.VisinaSeizmografa, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.VisinaSeizmografa, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <b class="control-label col-md-2">Latituda</b>
        <div class="col-md-10">
            @Html.EditorFor(model => model.LatitudaSeizmografa, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LatitudaSeizmografa, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <b class="control-label col-md-2">Longituda</b>
        <div class="col-md-10">
            @Html.EditorFor(model => model.LongitudaSeizmografa, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LongitudaSeizmografa, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Spremi" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Natrag na popis", "Index")
</div>

DZ04/SeizmoloskiZavod/SeizmoloskiZavod.Web/Views/Seizmografi/Index.cshtml
@using SeizmoloskiZavod.Bll;
@model IEnumerable<SeizmoloskiZavod.Bll.Seizmograf>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    IEnumerable<Postaja> postaje = ViewData["postaje"] as IEnumerable<Postaja>;
}

<p></p>

@Html.ActionLink("Izvrši mjerenja", "Mjerenje", "Seizmografi", null, new { @class = "btn btn-success" })

<h2>Seizmografi</h2>

<p>
    @Html.ActionLink("Stvori novi seizmograf", "Create", null, new { @class = "btn btn-default" })
</p>
<table class="table">
    <tr>
        <th>
            <b>Naziv</b>
        </th>
        <th>
            <b>Visina</b>
        </th>
        <th>
            <b>Latituda</b>
        </th>
        <th>
            <b>Longituda</b>
        </th>
        <th>
            <b>Naziv postaje</b>
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NazSeizmografa)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VisinaSeizmografa)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LatitudaSeizmografa)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LongitudaSeizmografa)
            </td>
            <td>
                @{
                    foreach (Postaja postaja in postaje)
                    {
                        if (postaja.IdPostaje == item.IdPostajeSeizmografa)
                        {
                            @Html.DisplayFor(modelItem => postaja.NazPostaje)
                        }
                    }
                }
            </td>
            <td>
                @Html.ActionLink("Ažuriraj", "Edit", new { id = item.IdSeizmografa }) |
                @Html.ActionLink("Detalji", "Details", new { id = item.IdSeizmografa })
            </td>
            <td>
                @using (Html.BeginForm("Delete", "Seizmografi", new { id = item.IdSeizmografa }))
                {
                    <button class="btn btn-danger">Obriši</button>
                }
            </td>
        </tr>
    }
</table>

DZ04/SeizmoloskiZavod/SeizmoloskiZavod.Web/Views/Seizmografi/Mjerenje.cshtml
@model SeizmoloskiZavod.Bll.SeizmografInfoList

@{
    ViewBag.Title = "Mjerenje";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<p></p>

<h4>Seizmografi</h4>
@using (Html.BeginForm("Mjerenje", "Seizmografi", FormMethod.Post))
{

    foreach (var item in Model)
    {
        <div class="checkbox">
            <input type="checkbox" id="@item.IdSeizmografa" name="@item.IdSeizmografa" />
            <label for="@item.IdSeizmografa">@item.NazSeizmografa</label>
        </div>
    }
    <button type="submit" class="btn btn-success btn-block">Pošalji zahtjeve za mjerenja</button>
}