Projekt/SeizmoloskiZavod.Web/Controllers/ObavijestiController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SeizmoloskiZavod.Bll;

namespace SeizmoloskiZavod.Web.Controllers
{
    public class ObavijestiController : Controller
    {
        public ActionResult Index()
        {
            var tipovi = TipObavijesti.Get().ToList();
            ViewData["tipovi"] = tipovi;
            var zaposlenici = Zaposlenik.Get().ToList();
            ViewData["zaposlenici"] = zaposlenici;
            return View(Obavijest.Get());
        }

        // GET: Obavijesti/Create
        public ActionResult Create()
        {
            ViewBag.IdTipovaList = new SelectList(TipObavijesti.Get(), "IdTipa", "NazTipa");
            ViewBag.IdZaposlenikaList = new SelectList(Zaposlenik.Get(), "IdZaposlenika", "KorisnickoImeZaposlenika");

            return View(Obavijest.New());
        }

        // POST: Obavijesti/Create
        [HttpPost]
        public ActionResult Create(string NaslovObavijesti, string SadrzajObavijesti, int IdTipaObavijesti, int IdZaposlenikaObavijesti)
        {

            Obavijest obavijest = Obavijest.New();
            try
            {
                obavijest.IdTipaObavijesti = IdTipaObavijesti;
                obavijest.IdZaposlenikaObavijesti = IdZaposlenikaObavijesti;
                obavijest.NaslovObavijesti = NaslovObavijesti;
                obavijest.SadrzajObavijesti = SadrzajObavijesti;
                obavijest.DatumVrijemeObavijesti = DateTime.Now;

                obavijest = obavijest.Save();
                return RedirectToAction("Index");
            }
            catch (Csla.Validation.ValidationException ex)
            {
                ViewBag.Pogreska = ex.Message;
                if (obavijest.BrokenRulesCollection.Count > 0)
                {
                    List<string> errors = new List<string>();
                    foreach (Csla.Validation.BrokenRule rule in obavijest.BrokenRulesCollection)
                    {
                        errors.Add(string.Format("{0}: {1}", rule.Property, rule.Description));
                        ModelState.AddModelError(rule.Property, rule.Description);
                    }
                    ViewBag.ErrorsList = errors;
                }
                return View(obavijest);
            }
            catch (Csla.DataPortalException ex)
            {
                ViewBag.Pogreska = ex.BusinessException.Message;
                return View(obavijest);
            }
            catch (Exception ex)
            {
                ViewBag.Pogreska = ex.Message;
                return View(obavijest);
            }
        }

        // GET: Obavijesti/Edit/5
        public ActionResult Edit(int id)
        {

            Obavijest obavijest = Obavijest.Get(id);
            ViewBag.IdTipovaList = new SelectList(TipObavijesti.Get(), "IdTipa", "NazTipa");
            ViewBag.IdZaposlenikaList = new SelectList(Zaposlenik.Get(), "IdZaposlenika", "KorisnickoImeZaposlenika");

            return View(obavijest);
        }

        // POST: Obavijesti/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, string NaslovObavijesti, string SadrzajObavijesti, int IdTipaObavijesti, int IdZaposlenikaObavijesti)
        {
            Obavijest obavijest = null;
            try
            {
                obavijest = Obavijest.Get(id);
                obavijest.NaslovObavijesti = NaslovObavijesti;
                obavijest.SadrzajObavijesti = SadrzajObavijesti;
                obavijest.IdTipaObavijesti = IdTipaObavijesti;
                obavijest.IdZaposlenikaObavijesti = IdZaposlenikaObavijesti;
                obavijest.DatumVrijemeObavijesti = DateTime.Now; ;
                obavijest.Save();
                return RedirectToAction("Index");
            }
            catch (Csla.Validation.ValidationException ex)
            {
                ViewBag.Pogreska = ex.Message;
                if (obavijest.BrokenRulesCollection.Count > 0)
                {
                    List<string> errors = new List<string>();
                    foreach (Csla.Validation.BrokenRule rule in obavijest.BrokenRulesCollection)
                    {
                        errors.Add(string.Format("{0}: {1}", rule.Property, rule.Description));
                        ModelState.AddModelError(rule.Property, rule.Description);
                    }
                    ViewBag.ErrorsList = errors;
                }
                return View(obavijest);
            }
            catch (Csla.DataPortalException ex)
            {
                ViewBag.Pogreska = ex.BusinessException.Message;
                return View(obavijest);
            }
            catch (Exception ex)
            {
                ViewBag.Pogreska = ex.Message;
                return View(obavijest);
            }
        }

        // POST: Obavijesti/Delete/5
        [HttpPost]
        public ActionResult Delete(int id)
        {
            try
            {
                Obavijest.Delete(id);
            }
            catch (Exception ex)
            {
                TempData["Pogreska"] = ex.Message;
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public string PromijeniTip(int IdObavijesti, int IdTipa)
        {
            try
            {
                Obavijest obavijest = Obavijest.Get(IdObavijesti);
                obavijest.IdTipaObavijesti = IdTipa;
                obavijest.Save();
                return "OK";
            }
            catch (Exception ex)
            {
                return ex.Message;
            }
        }
    }
}

Projekt/SeizmoloskiZavod.Web/Controllers/ZaposleniciController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SeizmoloskiZavod.Bll;

namespace SeizmoloskiZavod.Web.Controllers
{
    public class ZaposleniciController : Controller
    {
        // GET: Zaposlenici
        public ActionResult Index()
        {
            var uloge = Uloga.Get().ToList();
            ViewData["uloge"] = uloge;
            return View(Zaposlenik.Get());
        }

        // GET: Zaposlenici/Details/5
        public ActionResult Details(int id)
        {
            var obavijesti = Obavijest.Get().ToList();
            ViewData["obavijesti"] = obavijesti;
            ViewBag.IdTipovaList = new SelectList(TipObavijesti.Get(), "IdTipa", "NazTipa");

            return View(Zaposlenik.Get(id));
        }

        // GET: Zaposlenici/Create
        public ActionResult Create()
        {
            ViewBag.IdUlogeList = new SelectList(Uloga.Get(), "IdUloge", "NazUloge");
            return View(Zaposlenik.New());
        }

        // POST: Zaposlenici/Create
        [HttpPost]
        public ActionResult Create(int IdUlogeZaposlenika, string ImeZaposlenika, string PrezimeZaposlenika, string OIBZaposlenika, string KorisnickoImeZaposlenika, string LozinkaHashZaposlenika)
        {

            Zaposlenik zaposlenik = Zaposlenik.New();
            try
            { 
                zaposlenik.IdUlogeZaposlenika = IdUlogeZaposlenika;
                zaposlenik.ImeZaposlenika = ImeZaposlenika;
                zaposlenik.PrezimeZaposlenika = PrezimeZaposlenika;
                zaposlenik.OIBZaposlenika = OIBZaposlenika;
                zaposlenik.KorisnickoImeZaposlenika = KorisnickoImeZaposlenika;
                zaposlenik.LozinkaHashZaposlenika = LozinkaHashZaposlenika;
                zaposlenik = zaposlenik.Save();
                return RedirectToAction("Details", new { id = zaposlenik.IdZaposlenika });
            }
            catch (Csla.Validation.ValidationException ex)
            {
                ViewBag.Pogreska = ex.Message;
                if (zaposlenik.BrokenRulesCollection.Count > 0)
                {
                    List<string> errors = new List<string>();
                    foreach (Csla.Validation.BrokenRule rule in zaposlenik.BrokenRulesCollection)
                    {
                        errors.Add(string.Format("{0}: {1}", rule.Property, rule.Description));
                        ModelState.AddModelError(rule.Property, rule.Description);
                    }
                    ViewBag.ErrorsList = errors;
                }
                return View(zaposlenik);
            }
            catch (Csla.DataPortalException ex)
            {
                ViewBag.Pogreska = ex.BusinessException.Message;
                return View(zaposlenik);
            }
            catch (Exception ex)
            {
                ViewBag.Pogreska = ex.Message;
                return View(zaposlenik);
            }
        }

        // GET: Zaposlenici/Edit/5
        public ActionResult Edit(int id)
        {

            Zaposlenik zaposlenik = Zaposlenik.Get(id);
            ViewBag.IdUlogeList = new SelectList(Uloga.Get(), "IdUloge", "NazUloge");

            return View(zaposlenik);
        }

        // POST: Zaposlenici/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, int IdUlogeZaposlenika, string ImeZaposlenika, string PrezimeZaposlenika, string OIBZaposlenika, string KorisnickoImeZaposlenika, string LozinkaHashZaposlenika)
        {
            Zaposlenik zaposlenik = null;
            try
            {
                zaposlenik = Zaposlenik.Get(id);
                zaposlenik.IdUlogeZaposlenika = IdUlogeZaposlenika;
                zaposlenik.ImeZaposlenika = ImeZaposlenika;
                zaposlenik.PrezimeZaposlenika = PrezimeZaposlenika;
                zaposlenik.OIBZaposlenika = OIBZaposlenika;
                zaposlenik.KorisnickoImeZaposlenika = KorisnickoImeZaposlenika;
                zaposlenik.LozinkaHashZaposlenika = LozinkaHashZaposlenika;
                zaposlenik.Save();
                return RedirectToAction("Details", new { id = zaposlenik.IdZaposlenika });
            }
            catch (Csla.Validation.ValidationException ex)
            {
                ViewBag.Pogreska = ex.Message;
                if (zaposlenik.BrokenRulesCollection.Count > 0)
                {
                    List<string> errors = new List<string>();
                    foreach (Csla.Validation.BrokenRule rule in zaposlenik.BrokenRulesCollection)
                    {
                        errors.Add(string.Format("{0}: {1}", rule.Property, rule.Description));
                        ModelState.AddModelError(rule.Property, rule.Description);
                    }
                    ViewBag.ErrorsList = errors;
                }
                return View(zaposlenik);
            }
            catch (Csla.DataPortalException ex)
            {
                ViewBag.Pogreska = ex.BusinessException.Message;
                return View(zaposlenik);
            }
            catch (Exception ex)
            {
                ViewBag.Pogreska = ex.Message;
                return View(zaposlenik);
            }
        }

        // GET: Zaposlenici/Delete/5
        public ActionResult Delete(int id)
        {
            try
            {
                Zaposlenik.Delete(id);
            }
            catch (Exception ex)
            {
                TempData["Pogreska"] = ex.Message;
                return RedirectToAction("/Details", new { id = id });
            }
            return RedirectToAction("Index");
        }
    }
}

Projekt/SeizmoloskiZavod.Web/Views/Zaposlenici/Create.cshtml
@model SeizmoloskiZavod.Bll.Zaposlenik

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Stvaranje novog zaposlenika</h2>

@using (Html.BeginForm())
{
<div class="form-horizontal">
    <h4>Zaposlenik</h4>
    <hr />
    <div class="form-group">
        <b class="control-label col-md-2">Ime</b>
        <div class="col-md-10">
            @Html.EditorFor(model => model.ImeZaposlenika, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>

    <div class="form-group">
        <b class="control-label col-md-2">Prezime</b>
        <div class="col-md-10">
            @Html.EditorFor(model => model.PrezimeZaposlenika, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>

    <div class="form-group">
        <b class="control-label col-md-2">OIB</b>
        <div class="col-md-10">
            @Html.EditorFor(model => model.OIBZaposlenika, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>

    <div class="form-group">
        <b class="control-label col-md-2">Korisnicko ime</b>
        <div class="col-md-10">
            @Html.EditorFor(model => model.KorisnickoImeZaposlenika, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>

    <div class="form-group">
        <b class="control-label col-md-2">Hash lozinke</b>
        <div class="col-md-10">
            @Html.EditorFor(model => model.LozinkaHashZaposlenika, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>

    <div class="form-group">
        <b class="control-label col-md-2">Uloga</b>
        <div class="col-md-10">
            @Html.DropDownListFor(m => m.IdUlogeZaposlenika, (SelectList)ViewBag.IdUlogeList,
            null, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.IdUlogeZaposlenika, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Spremi" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Natrag na popis", "Index")
</div>

Projekt/SeizmoloskiZavod.Web/Views/Zaposlenici/Delete.cshtml
@model SeizmoloskiZavod.Bll.Zaposlenik

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Zaposlenik</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            <b>Ime</b>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImeZaposlenika)
        </dd>

        <dt>
            <b>Prezime</b>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PrezimeZaposlenika)
        </dd>

        <dt>
            <b>OIB</b>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OIBZaposlenika)
        </dd>

        <dt>
            <b>Korisničko ime</b>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KorisnickoImeZaposlenika)
        </dd>

        <dt>
            <b>Hash lozinke</b>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LozinkaHashZaposlenika)
        </dd>

        <dt>
            <b>Uloga</b>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UlogaZaposlenika)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {

        <div class="form-actions no-color">
            <input type="submit" value="Obriši" class="btn btn-default" /> |
            @Html.ActionLink("Natrag na popis", "Index")
        </div>
    }
</div>

Projekt/SeizmoloskiZavod.Web/Views/Zaposlenici/Details.cshtml
@using SeizmoloskiZavod.Bll
@model SeizmoloskiZavod.Bll.Zaposlenik

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
    IEnumerable<Obavijest> obavijesti = ViewData["obavijesti"] as IEnumerable<Obavijest>;
    IEnumerable<TipObavijesti> tipovi = ViewData["tipovi"] as IEnumerable<TipObavijesti>;
    List<SeizmoloskiZavod.Bll.TipObavijesti> listaTipova = TipObavijesti.Get();

}

<script src="../../Scripts/jquery-1.5.1-vsdoc.js" type="text/javascript"></script>


<h2>Detalji</h2>

<div>
    <h4>Zaposlenik</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            <b>Uloga</b>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UlogaZaposlenika)
        </dd>
        <dt>
            <b>Ime</b>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImeZaposlenika)
        </dd>
        <dt>
            <b>Prezime</b>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PrezimeZaposlenika)
        </dd>

        <dt>
            <b>OIB</b>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OIBZaposlenika)
        </dd>

        <dt>
            <b>Korisnicko Ime</b>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KorisnickoImeZaposlenika)
        </dd>

        <dt>
            <b>Hash lozinke</b>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LozinkaHashZaposlenika)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Ažuriraj", "Edit", new { id = Model.IdZaposlenika }) |
    @Html.ActionLink("Natrag na popis", "Index")
</p>

<h2>Postavljene obavijesti</h2>

<table class="table">
    <tr>
        <th>
            <b>Naslov</b>
        </th>
        <th>
            <b>Sadržaj</b>
        </th>
        <th>
            <b>Tip</b>
        </th>
        <th></th>
    </tr>

    @{
        foreach (Obavijest obavijest in obavijesti)
        {
            if (obavijest != null && obavijest.IdZaposlenikaObavijesti == Model.IdZaposlenika)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => obavijest.NaslovObavijesti)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => obavijest.SadrzajObavijesti)
                    </td>
                    <td>
                        @Html.DropDownListFor(m => obavijest.IdTipaObavijesti, new SelectList(listaTipova, "IdTipa", "NazTipa", obavijest.IdTipaObavijesti), 
                            new { @class = "form-control", data_idobavijesti=obavijest.IdObavijesti })
                        <span class="rezultat"></span>
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => obavijest.ZaposlenikObavijesti)
                    </td>

                    <td>
                        @using (Html.BeginForm("Delete", "Obavijesti", new { id = obavijest.IdObavijesti }))
                        {
                            <button class="btn btn-danger">Obriši</button>
                        }
                    </td>
                </tr>

            }
        }
    }

</table>


<script type="text/javascript" language="javascript">
    $(function () {
        $('.form-control').each(function () { // svakoj kontroli s css klasom ddlUloga
            $(this).change(function () {
                // dodaje se kod događaja pri promjeni odabranog u listi
                var span = $(this).parent().find(".rezultat").first(); // span pored liste za rezultat
                var idtipa = $(this).val();
                // odabrani value u listi, vlastiti atribut sif, vlastiti atribut idosobe, prostor za rezultat
                promijeniTip($(this).data('idobavijesti'), idtipa, span);
            }
            );
        }
        );
    }
    );

    // ajax post zahtjev na controller
    // vrti se na klijentu ali šalje .post na server
    function promijeniTip(idobavijesti, idtipa, span) {
        // pozovem kontroler Projekt, akciju PromijeniUlogu
        $.post("../../Obavijesti/PromijeniTip",
            { IdObavijesti: idobavijesti, IdTipa: idtipa },
            function (data) {  // nakon izvršavanja sa servera
                $(span).html('').fadeIn(); // počisti span
                if (data == 'OK') { // pokaži OK i nestani
                    $(span).html(data).fadeOut(1000); // ... nakon 1s
                }
                else { // pokaži što je vratio server, npr. error
                    $(span).html(data);
                }
            }
        );
    }
</script>

Projekt/SeizmoloskiZavod.Web/Views/Zaposlenici/Edit.cshtml
@model SeizmoloskiZavod.Bll.Zaposlenik

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Ažuriranje</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Zaposlenik</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.IdZaposlenika)

    <div class="form-group">
        <b class="control-label col-md-2">Uloga</b>
        <div class="col-md-10">
            @Html.DropDownListFor(m => m.IdUlogeZaposlenika, (SelectList)ViewBag.IdUlogeList,
            null, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.IdUlogeZaposlenika, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <b class="control-label col-md-2">Ime</b>
        <div class="col-md-10">
            @Html.EditorFor(model => model.ImeZaposlenika, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ImeZaposlenika, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <b class="control-label col-md-2">Prezime</b>
        <div class="col-md-10">
            @Html.EditorFor(model => model.PrezimeZaposlenika, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PrezimeZaposlenika, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <b class="control-label col-md-2">OIB</b>
        <div class="col-md-10">
            @Html.EditorFor(model => model.OIBZaposlenika, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.OIBZaposlenika, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <b class="control-label col-md-2">Korisnicko ime</b>
        <div class="col-md-10">
            @Html.EditorFor(model => model.KorisnickoImeZaposlenika, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.KorisnickoImeZaposlenika, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <b class="control-label col-md-2">Hash lozinke</b>
        <div class="col-md-10">
            @Html.EditorFor(model => model.LozinkaHashZaposlenika, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LozinkaHashZaposlenika, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Spremi" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Natrag na popis", "Index")
</div>

Projekt/SeizmoloskiZavod.Web/Views/Zaposlenici/Index.cshtml
@using SeizmoloskiZavod.Bll;
@model IEnumerable<SeizmoloskiZavod.Bll.Zaposlenik>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    IEnumerable<Uloga> uloge = ViewData["uloge"] as IEnumerable<Uloga>;
}

<h2>Zaposlenici</h2>

<p>
    @Html.ActionLink("Stvori novog zaposlenika", "Create", null, new { @class = "btn btn-default" })
</p>
<table class="table">
    <tr>
        <th>
            <b>Uloga</b>
        </th>

        <th>
            <b>Ime</b>
        </th>
        <th>
            <b>Prezime</b>
        </th>
        <th>
            <b>OIB</b>
        </th>
        <th>
            <b>Korisnicko ime</b>
        </th>
        <th>
            <b>Hash lozinke</b>
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
    <tr>
        <td>
            @{
                foreach (Uloga uloga in uloge)
                {
                    if (uloga.IdUloge == item.IdUlogeZaposlenika)
                    {
                        @Html.DisplayFor(modelItem => uloga.NazUloge)
                    }
                }
            }
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ImeZaposlenika)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PrezimeZaposlenika)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OIBZaposlenika)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.KorisnickoImeZaposlenika)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LozinkaHashZaposlenika)
        </td>
        <td>
            @Html.ActionLink("Ažuriraj", "Edit", new { id = item.IdZaposlenika }) |
            @Html.ActionLink("Detalji", "Details", new { id = item.IdZaposlenika })
        </td>
        <td>
            @using (Html.BeginForm("Delete", "Zaposlenici", new { id = item.IdZaposlenika }))
            {
                <button class="btn btn-danger">Obriši</button>
            }
        </td>
    </tr>
    }
</table>